### ISSUE TITLE
Cannot edit existing aliases

### ISSUE THREAD

**Issue by blake-mealey** [sean-smith/chromeshortcuts#3]
If I make a mistake I have to add a new one (and clear them all as per #1 ).

You're probably already aware of this but figured I'd get the ball rolling with this issue. I may have time to submit a PR soon.

**Comment by sean-smith** [comment]
Awesome, thanks @blake-mealey

**Comment by sean-smith** [comment]
@blake-mealey I've added the ability remove individual aliases (pending publishing in the chrome webstore) I think this should resolve your issue

**Comment by blake-mealey** [comment]
Hmm, when I try using this feature now, it always deletes the first alias in my list instead of the one I clicked the X on :(

**Comment by sean-smith** [comment]
uh oh

**Comment by sean-smith** [comment]
Ok, I was able to reproduce the issue and figure out where it's coming from.

**Comment by sean-smith** [comment]
Will fix it shortly
